### ISSUE TITLE
File not found - darwin

### ISSUE THREAD

**Issue by superbonaci** [BDisp/unlocker#23]
OS: windows 11
Error:
````
win-install.cmd

Unlocker 3.0.4 for VMware Workstation
=====================================
(c) Dave Parsons 2011-18

Set encoding parameters...
Active code page: 850

VMware is installed at: C:\Program Files (x86)\VMware\VMware Workstation\
VMware product version: 16.2.3.19376536

Stopping VMware services...

Backing up files...
C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx.exe -> D:\BDisp-osx-unlocker\backup-windows\x64\vmware-vmx.exe
1 File(s) copied
C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-debug.exe -> D:\BDisp-osx-unlocker\backup-windows\x64\vmware-vmx-debug.exe
1 File(s) copied
C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-stats.exe -> D:\BDisp-osx-unlocker\backup-windows\x64\vmware-vmx-stats.exe
1 File(s) copied
C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll -> D:\BDisp-osx-unlocker\backup-windows\vmwarebase.dll
1 File(s) copied

Patching...
File: C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx.exe

appleSMCTableV0 (smc.version = "0")
appleSMCTableV0 Address      : 0xc46b70
appleSMCTableV0 Private Key #: 0xF2/242
appleSMCTableV0 Public Key  #: 0xF0/240
appleSMCTableV0 Table        : 0xc46b90
+LKS Key:
002 0xc46bd8 +LKS 01 flag 0x90 0x1401f1080 07
OSK0 Key Before:
241 0xc4af10 OSK0 32 ch8* 0x80 0x1401f1100 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
OSK0 Key After:
241 0xc4af10 OSK0 32 ch8* 0x80 0x1401f1080 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
242 0xc4af58 OSK1 32 ch8* 0x80 0x1401f1100 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
OSK1 Key After:
242 0xc4af58 OSK1 32 ch8* 0x80 0x1401f1080 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

appleSMCTableV1 (smc.version = "1")
appleSMCTableV1 Address      : 0xc4afa0
appleSMCTableV1 Private Key #: 0x01B4/436
appleSMCTableV1 Public Key  #: 0x01B0/432
appleSMCTableV1 Table        : 0xc4afc0
+LKS Key:
004 0xc4b098 +LKS 01 flag 0x90 0x1401f1080 01
OSK0 Key Before:
435 0xc529d0 OSK0 32 ch8* 0x90 0x1401f1100 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
OSK0 Key After:
435 0xc529d0 OSK0 32 ch8* 0x90 0x1401f1080 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
436 0xc52a18 OSK1 32 ch8* 0x90 0x1401f1100 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
OSK1 Key After:
436 0xc52a18 OSK1 32 ch8* 0x90 0x1401f1080 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

File: C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-debug.exe

appleSMCTableV0 (smc.version = "0")
appleSMCTableV0 Address      : 0xee18b0
appleSMCTableV0 Private Key #: 0xF2/242
appleSMCTableV0 Public Key  #: 0xF0/240
appleSMCTableV0 Table        : 0xee18d0
+LKS Key:
002 0xee1918 +LKS 01 flag 0x90 0x140263b00 07
OSK0 Key Before:
241 0xee5c50 OSK0 32 ch8* 0x80 0x140263cd0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
OSK0 Key After:
241 0xee5c50 OSK0 32 ch8* 0x80 0x140263b00 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
242 0xee5c98 OSK1 32 ch8* 0x80 0x140263cd0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
OSK1 Key After:
242 0xee5c98 OSK1 32 ch8* 0x80 0x140263b00 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

appleSMCTableV1 (smc.version = "1")
appleSMCTableV1 Address      : 0xee5ce0
appleSMCTableV1 Private Key #: 0x01B4/436
appleSMCTableV1 Public Key  #: 0x01B0/432
appleSMCTableV1 Table        : 0xee5d00
+LKS Key:
004 0xee5dd8 +LKS 01 flag 0x90 0x140263b00 01
OSK0 Key Before:
435 0xeed710 OSK0 32 ch8* 0x90 0x140263cd0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
OSK0 Key After:
435 0xeed710 OSK0 32 ch8* 0x90 0x140263b00 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
436 0xeed758 OSK1 32 ch8* 0x90 0x140263cd0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
OSK1 Key After:
436 0xeed758 OSK1 32 ch8* 0x90 0x140263b00 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

File: C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-stats.exe

appleSMCTableV0 (smc.version = "0")
appleSMCTableV0 Address      : 0xc9e290
appleSMCTableV0 Private Key #: 0xF2/242
appleSMCTableV0 Public Key  #: 0xF0/240
appleSMCTableV0 Table        : 0xc9e2b0
+LKS Key:
002 0xc9e2f8 +LKS 01 flag 0x90 0x140200430 07
OSK0 Key Before:
241 0xca2630 OSK0 32 ch8* 0x80 0x1402004b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
OSK0 Key After:
241 0xca2630 OSK0 32 ch8* 0x80 0x140200430 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
242 0xca2678 OSK1 32 ch8* 0x80 0x1402004b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
OSK1 Key After:
242 0xca2678 OSK1 32 ch8* 0x80 0x140200430 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

appleSMCTableV1 (smc.version = "1")
appleSMCTableV1 Address      : 0xca26c0
appleSMCTableV1 Private Key #: 0x01B4/436
appleSMCTableV1 Public Key  #: 0x01B0/432
appleSMCTableV1 Table        : 0xca26e0
+LKS Key:
004 0xca27b8 +LKS 01 flag 0x90 0x140200430 01
OSK0 Key Before:
435 0xcaa0f0 OSK0 32 ch8* 0x90 0x1402004b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
OSK0 Key After:
435 0xcaa0f0 OSK0 32 ch8* 0x90 0x140200430 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
436 0xcaa138 OSK1 32 ch8* 0x90 0x1402004b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
OSK1 Key After:
436 0xcaa138 OSK1 32 ch8* 0x90 0x140200430 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

GOS Patching: C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll
GOS Patched flag @: 0x4d44d8
GOS Patched flag @: 0x4d4518
GOS Patched flag @: 0x4d4558
GOS Patched flag @: 0x4d4598
GOS Patched flag @: 0x4d45d8
GOS Patched flag @: 0x4d4618
GOS Patched flag @: 0x4d4658
GOS Patched flag @: 0x4d4698
GOS Patched flag @: 0x4d46d8
GOS Patched flag @: 0x4d4718
GOS Patched flag @: 0x4d4758
GOS Patched flag @: 0x4d4798
GOS Patched flag @: 0x4d47d8
GOS Patched flag @: 0x4d4818
GOS Patched flag @: 0x4d4858
GOS Patched flag @: 0x4d4898
GOS Patched flag @: 0x4d48d8
GOS Patched flag @: 0x584f38
GOS Patched flag @: 0x584f78
GOS Patched flag @: 0x584fb8
GOS Patched flag @: 0x584ff8
GOS Patched flag @: 0x585038
GOS Patched flag @: 0x585078
GOS Patched flag @: 0x5850b8
GOS Patched flag @: 0x5850f8
GOS Patched flag @: 0x585138
GOS Patched flag @: 0x585178
GOS Patched flag @: 0x5851b8
GOS Patched flag @: 0x5851f8
GOS Patched flag @: 0x585238
GOS Patched flag @: 0x585278
GOS Patched flag @: 0x5852b8
GOS Patched flag @: 0x5852f8
GOS Patched flag @: 0x585338
GOS Patched: C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll

Getting VMware Tools...
Trying to get tools from the packages folder...
Traceback (most recent call last):
  File "urllib\request.py", line 1350, in do_open
  File "http\client.py", line 1262, in request
  File "http\client.py", line 1308, in _send_request
  File "http\client.py", line 1257, in endheaders
  File "http\client.py", line 1028, in _send_output
  File "http\client.py", line 968, in send
  File "http\client.py", line 940, in connect
  File "socket.py", line 707, in create_connection
  File "socket.py", line 752, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gettools.py", line 286, in <module>
    print('Tools from package retrieved successfully')
  File "gettools.py", line 147, in main
    # Get the list of Fusion releases
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 543, in _open
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 1378, in http_open
  File "urllib\request.py", line 1352, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
[20704] Failed to execute script 'gettools' due to unhandled exception!
File not found - darwin*.*
0 File(s) copied

Starting VMware services...

Finished!
````

**Comment by BDisp** [comment]
In what VMware version?

**Comment by BDisp** [comment]
I installed the VMware Workstation version 16 Pro16.2.3 build-19376536 and I haven't any issue. Probably you install again on an already patched version. It's better to reinstall VMware software.

**Comment by superbonaci** [comment]
I ran the unpatch before upgrading, but maybe a full uninstall is required.
